<%
select case fcount

case "a0"
  fname="cover.jpg"
  ftext="Living in the service of a clan known as the ShadowBlades,Skat has lived in a web of secrets since the beginning of his life. One day he gets a visit from an old friend named Strix. The visit came with a mission from the ShadowBlade leaders requesting Skat to convince the Mayor Bawer of the Dog Village to build a special battle ship that would surpass any they have ever made before. The greedy mayor would agree to build the super battleship under one condition,Bawer wanted Skat to steal a rare stone called the Gemini crystal from the Wolf Tribe. By the time mayor Bawer had the super battleship under construction,Skat had made many enemies who were now tracking him down."
  choice1="<A HREF=""index.asp?page=a1"" >Click</A>"
  choice2="<A HREF=""index.asp?page=a1"" >Here</A>"

case "a1"
  fname="a1.jpg"
  ftext="Kendrick is informed that someone has taken his Gemini crystal. He needs to know who took it, and get it back."
  choice1="<A HREF=""index.asp?page=a2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=a2"" >Here</A>"

case "a2"
  fname="a2.jpg"
  ftext="Kendrick calls on his most trusted troops, Nachi, and Boomer. They must go out in search of the Gemini crystal. The two leave immediately."
  choice1="<A HREF=""index.asp?page=a3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=a3"" >Here</A>"

case "a3"
  fname="a3.jpg"
  ftext="Their trail leads the two wolf soldiers to a neighboring dog town called Barnard. The wolves head straight towards the mayors building. The mayor denies any part in the Gemini crystals disappearance. The mayor continues to lie when he tells the two soldiers that a local called Skat, has taken their crystal with plans to sell it."
  choice1="<A HREF=""index.asp?page=a4"" >Click</A>"
  choice2="<A HREF=""index.asp?page=a4"" >Here</A>"

case "a4"
  fname="a4.jpg"
  ftext="The mayor tells them where they can find Skat. Boomer and Nachi decide to look into the possible suspect's story. The two wolves bang on Skat's door."
  choice1="<A HREF=""index.asp?page=a5"" >Click</A>"
  choice2="<A HREF=""index.asp?page=a5"" >Here</A>"

case "a5"
  fname="a5.jpg"
  ftext="Curiously, Skat peaks out to see who's at his door. He sees the two wolves, and he knows why they're there. Should he leave and avoid an obvious confrontation? Or should he open the door and deny any knowledge of the missing crystal?"
  choice1="<A HREF=""index.asp?page=b1"" >Sneak out the back.</A>"
  choice2="<A HREF=""index.asp?page=c1"" >Open the door and fight.</A>"

case "b1"
  fname="b1.jpg"
  ftext="Skat sneaks out the back wondering how they could have found him. He decides to hideout in the 'Neutral village'. As he moves through the woods a giant green dragon roars towards Skat in a loud attack."
  choice1="<A HREF=""index.asp?page=b2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=b2"" >Here</A>"

case "b2"
  fname="b2.jpg"
  ftext="Familiar with these types of dragons, Skat kills it quickly. He then hears an identical roaring nearby. It sounds as if someone else is being attacked. Skat goes to investigate."
  choice1="<A HREF=""index.asp?page=b3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=b3"" >Here</A>"

case "b3"
  fname="b3.jpg"
  ftext="It's the two wolf soldiers that were banging on Skat's door. Apparently, they knew Skat went out the back. And when they tried to follow him, they got attacked by this dragon. They're in trouble now. Should Skat help them out?"
  choice1="<A HREF=""index.asp?page=d1"" >Leave, and let them take care of it.</A>"
  choice2="<A HREF=""index.asp?page=e1"" >Help the two wolf soldiers.</A>"

case "c1"
  fname="c1.jpg"
  ftext="Confident, Skat opens his door 'What?!' He asks with an annoyed tone. The wolves begin to ask him questions. Skat gets more annoyed and the conversation starts getting loud."
  choice1="<A HREF=""index.asp?page=c2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=c2"" >Here</A>"

case "c2"
  fname="c2.jpg"
  ftext="Skat attacks both the wolves. The fight doesn't lasts too long.  "
  choice1="<A HREF=""index.asp?page=c3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=c3"" >Here</A>"

case "c3"
  fname="c3.jpg"
  ftext="With a swift strike to the back, Skat kills Nachi. Boomer, the other wolf soldier retreats. Should Skat run after him?"
  choice1="<A HREF=""index.asp?page=f1"" >Go after the fleeing wolf.</A>"
  choice2="<A HREF=""index.asp?page=g1"" >Leave dog town and find help.</A>"

case "d1"
  fname="d1.jpg"
  ftext="Skat moves on to the 'Neutral village'. This is a place of bartering and trading. You can find all types of people here. It has no real ruler. Skat walks into a restaurant and orders some food."
  choice1="<A HREF=""index.asp?page=d2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=d2"" >Here</A>"

case "d2"
  fname="d2.jpg"
  ftext="While eating Skat is approached by Two rabbit samurai from an opposing clan called the FireBlades. Ryuho and his brother Sakara walk closer. Skat ignores them and continues to eat his meal."
  choice1="<A HREF=""index.asp?page=d3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=d3"" >Here</A>"

case "d3"
  fname="d3.jpg"
  ftext="Sakara interrupts by grabbing Skat's food and throwing it to the side. The rabbits challenge Skat to a formal duel. Should Skat fight both of these warriors, or should he RUN?"
  choice1="<A HREF=""index.asp?page=h1"" >Fight both of the samurai rabbits at once.</A>"
  choice2="<A HREF=""index.asp?page=i1"" >Run!</A>"

case "e1"
  fname="e1.jpg"
  ftext="Skat jumps up to the harvest dragon and slices it's head off using his dragon star. The wolves are grateful and agree to accompany Skat to the 'Neutral village'."
  choice1="<A HREF=""index.asp?page=e2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=e2"" >Here</A>"

case "e2"
  fname="e2.jpg"
  ftext="They reach the ' Neutral village'. Most of the stores and shops are closed. Day break should be coming soon."
  choice1="<A HREF=""index.asp?page=e3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=e3"" >Here</A>"

case "e3"
  fname="e3.jpg"
  ftext="Slowly, two figures appear out from the shadows. Two rabbit samurai. The one named Sakara starts talking 'We are from the FireBlades. Warriors of the sword! And you're kind is not welcomed here. We challenge you to a fight. Do you accept?' Should Skat put his team to the test, or should they all RUN!"
  choice1="<A HREF=""index.asp?page=j1"" >Pit you're team against the two samurai.</A>"
  choice2="<A HREF=""index.asp?page=k1"" >Retreat to a safe location.</A>"

case "f1"
  fname="f1.jpg"
  ftext="The small wolf called Boomer escapes with his life. Skat follows close behind as Boomer leads him towards his village."
  choice1="<A HREF=""index.asp?page=f2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=f2"" >Here</A>"

case "f2"
  fname="f2.jpg"
  ftext="'Kendrick!' Boomer yells for his leader to come out. In just a few moments Skat is surrounded by dozens of wolves. Boomer tells Kendrick of Nachi's death at the hands of Skat. 'The mayor at the town said he was the one who took the Gemini crystal, Master' The small wolf talks fast as he attempts to catch his breath."
  choice1="<A HREF=""index.asp?page=f3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=f3"" >Here</A>"

case "f3"
  fname="f3.jpg"
  ftext="With his troops behind him Kendrick runs up to Skat and grabs him 'Where is it?! What did you do with the crystal?' Skat looks on with silence. Frustrated, Kendrick makes Skat choose one of two styles of fighting. Fight hand to hand or fight with swords?"
  choice1="<A HREF=""index.asp?page=l1"" >Fight Kendrick with sword.</A>"
  choice2="<A HREF=""index.asp?page=m1"" >Fight Kendrick hand to hand.</A>"

case "g1"
  fname="g1.jpg"
  ftext="With great speed Skat runs through the forest. Night soon falls upon him and he stops moving to setup camp. Using the corpse of a harvest dragon he makes a tent and goes to sleep."
  choice1="<A HREF=""index.asp?page=g2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=g2"" >Here</A>"

case "g2"
  fname="g2.jpg"
  ftext="During the night he is awakened by the a strange sound. Skat has never heard anything like it. He moves towards it with much curiosity."
  choice1="<A HREF=""index.asp?page=g3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=g3"" >Here</A>"

case "g3"
  fname="g3.jpg"
  ftext="As Skat peers over some bushes a small gray creature comes into view. The weird looking guy cries out loud. With his curiosity satisfied, Skat goes back to his camp."
  choice1="<A HREF=""index.asp?page=g4"" >Click</A>"
  choice2="<A HREF=""index.asp?page=g4"" >Here</A>"

case "g4"
  fname="g4.jpg"
  ftext="Moments later another loud noise 'Grrowl!!' This is not the sound of someone crying. Skat heads back to see what's going on. The small creature is being attacked by a huge pig warrior. Skat wonders whether he should help the gray guy or let them fight?"
  choice1="<A HREF=""index.asp?page=n1"" >Attack the large pig.</A>"
  choice2="<A HREF=""index.asp?page=o1"" >See what happens.</A>"

case "h1"
  fname="h1.jpg"
  ftext="Silently, Skat stands up. Skat uses this uncomfortable silence to mentally throw off his two opponents."
  choice1="<A HREF=""index.asp?page=h2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=h2"" >Here</A>"

case "h2"
  fname="h2.jpg"
  ftext="Suddenly, Skat jumps into the air grabbing his dragon star and throwing it at Sakara. The star hits Sakara's shoulder."
  choice1="<A HREF=""index.asp?page=h3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=h3"" >Here</A>"

case "h3"
  fname="h3.jpg"
  ftext="Ryuho moves in without hesitation. Skat draws out his sword just in time to meet Ryuho's blade. The two are locked in battle for a while. As the two continue their fight it's hard to tell which warrior is winning."
  choice1="<A HREF=""index.asp?page=h4"" >Click</A>"
  choice2="<A HREF=""index.asp?page=h4"" >Here</A>"

case "h4"
  fname="h4.jpg"
  ftext="Sakara, still angered by Skat's initial attack moves in and stabs Skat in the back, killing him. The rabbit samurai from the FireBlade clan have won today's battle."
  choice1="<A HREF=""index.asp?page=a0"" >The</A>"
  choice2="<A HREF=""index.asp?page=a0"" >End</A>"

case "i1"
  fname="i1.jpg"
  ftext="Skat runs away again but is soon ambushed by the two wolf soldiers and the two samurai warriors."
  choice1="<A HREF=""index.asp?page=i2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=i2"" >Here</A>"

case "i2"
  fname="i2.jpg"
  ftext="Skat finally decides to stand his ground and fight, but it's too late."
  choice1="<A HREF=""index.asp?page=i3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=i3"" >Here</A>"

case "i3"
  fname="i3.jpg"
  ftext="All his enemies come together and beat him to  a painful death. Leaving Skat's corpse on the ground, broken."
  choice1="<A HREF=""index.asp?page=a0"" >The</A>"
  choice2="<A HREF=""index.asp?page=a0"" >End</A>"

case "j1"
  fname="j1.jpg"
  ftext="Skat gives the wolves the signal to attack. Ryuho quickly locks himself in a fierce sword fight with Skat as the two wolves team up against Sakara. The wolves have Sakara on the ground and secured almost instantly."
  choice1="<A HREF=""index.asp?page=j2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=j2"" >Here</A>"

case "j2"
  fname="j2.jpg"
  ftext="Skat is having some trouble with Ryuho. Skat has never met anyone as good with a sword as he is. Could Skat have finally met his equal? "
  choice1="<A HREF=""index.asp?page=j3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=j3"" >Here</A>"

case "j3"
  fname="j3.jpg"
  ftext="The fight lasts long, and after some time goes by both Skat and Ryuho get too tired to even swing their swords at each other."
  choice1="<A HREF=""index.asp?page=j4"" >Click</A>"
  choice2="<A HREF=""index.asp?page=j4"" >Here</A>"

case "j4"
  fname="j4.jpg"
  ftext="'Why don't we just call it a draw?' Ryuho says. Skat agrees, and explains the story to the samurai rabbits. Ryuho and Sakara join Skat's growing team of fighters, and vow to never fight against each other again."
  choice1="<A HREF=""index.asp?page=a0"" >The</A>"
  choice2="<A HREF=""index.asp?page=a0"" >End</A>"

case "k1"
  fname="k1.jpg"
  ftext="Skat yells for his team to run. Ryuho and Sakara laugh as they all retreat into the woods."
  choice1="<A HREF=""index.asp?page=k2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=k2"" >Here</A>"

case "k2"
  fname="k2.jpg"
  ftext="After reching the safety of the forest the two wolf soldier consider Skat as a coward and walk away, leaving his team."
  choice1="<A HREF=""index.asp?page=k3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=k3"" >Here</A>"

case "k3"
  fname="k3.jpg"
  ftext="Skat is left in the woods alone and never heard from again. Some say he changed his name and became a preist."
  choice1="<A HREF=""index.asp?page=a0"" >The</A>"
  choice2="<A HREF=""index.asp?page=a0"" >End</A>"

case "l1"
  fname="l1.jpg"
  ftext="Skat feels alive when his sword is in his grasp. He swings it with ease. It comes as natural to him as breathing."
  choice1="<A HREF=""index.asp?page=l2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=l2"" >Here</A>"

case "l2"
  fname="l2.jpg"
  ftext="Kendrick charges Skat with his large sword and the two warriors clash swords. Sparks flying swords clingging."
  choice1="<A HREF=""index.asp?page=l3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=l3"" >Here</A>"

case "l3"
  fname="l3.jpg"
  ftext="But in the end Skat stands victorious as Kendrick's body splits in two. All the wolves watching can't believe their leader has just been defeated. None of the wolves try to fight Skat as he leaves the village."
  choice1="<A HREF=""index.asp?page=a0"" >The</A>"
  choice2="<A HREF=""index.asp?page=a0"" >End</A>"

case "m1"
  fname="m1.jpg"
  ftext="Even though the sword is his favorite weapon Skat feels confident in using his hands to fight the powerful Kendrick."
  choice1="<A HREF=""index.asp?page=m2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=m2"" >Here</A>"

case "m2"
  fname="m2.jpg"
  ftext="Both warriors posses great fighting abilities. They're both quick and strong."
  choice1="<A HREF=""index.asp?page=m3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=m3"" >Here</A>"

case "m3"
  fname="m3.jpg"
  ftext="But without his sword Skat is incomplete, and Kendrick overpowers Skat and breaks his neck. "
  choice1="<A HREF=""index.asp?page=a0"" >The</A>"
  choice2="<A HREF=""index.asp?page="" >End</A>"

case "n1"
  fname="n1.jpg"
  ftext="Skat feels bad for the little guy, and rushes in stabbing the large pig warrior. The gray creature stands in surprise as he sees his opponent drop dead before him."
  choice1="<A HREF=""index.asp?page=n2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=n2"" >Here</A>"

case "n2"
  fname="n2.jpg"
  ftext="'Thank you.' The creature says. 'My name is Vexx and one day I shall repay you.' Vexx smiles and then runs off."
  choice1="<A HREF=""index.asp?page=n3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=n3"" >Here</A>"

case "n3"
  fname="n3.jpg"
  ftext="As Vexx disapears into the woods Skat wonders to himself 'What the hell was that all about?'"
  choice1="<A HREF=""index.asp?page=a0"" >The</A>"
  choice2="<A HREF=""index.asp?page=a0"" >End</A>"

case "o1"
  fname="o1.jpg"
  ftext="Skat stands back and watches the two fight. The small creature seems to be keeping up with his larger opponent until the pig warrior hits him with a powerful punch that sends him flying into a tree."
  choice1="<A HREF=""index.asp?page=o2"" >Click</A>"
  choice2="<A HREF=""index.asp?page=o2"" >Here</A>"

case "o2"
  fname="o2.jpg"
  ftext="The small creature slowly stands up, enraged he lets out a loud scream as he bursts into flames. This site amazes both Skat and the pig warrior."
  choice1="<A HREF=""index.asp?page=o3"" >Click</A>"
  choice2="<A HREF=""index.asp?page=o3"" >Here</A>"

case "o3"
  fname="o3.jpg"
  ftext="The creature attacks the pig with a great rush of fire. Leaving nothing but ashes and a tarnished chain which the pig wore around his neck."
  choice1="<A HREF=""index.asp?page=o4"" >Click</A>"
  choice2="<A HREF=""index.asp?page=o4"" >Here</A>"

case "o4"
  fname="o4.jpg"
  ftext="Realizing that someone had been watching all this time the small gray creature looks on at Skat. His flames die down and he begins to talk 'He disevrved it. 'With those words the creature escapes into the woods. Skat stands there and wonders to himself 'What the hell was all that about?'"
  choice1="<A HREF=""index.asp?page=a0"" >The</A>"
  choice2="<A HREF=""index.asp?page=a0"" >End</A>"

end select
%>